# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/strawberry/acy/develop2/themis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/strawberry/acy/develop2/themis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/strawberry/acy/develop2/themis/CMakeFiles /home/strawberry/acy/develop2/themis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/strawberry/acy/develop2/themis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named themis

# Build rule for target.
themis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 themis
.PHONY : themis

# fast build rule for target.
themis/fast:
	$(MAKE) -f CMakeFiles/themis.dir/build.make CMakeFiles/themis.dir/build
.PHONY : themis/fast

strconv.o: strconv.cpp.o

.PHONY : strconv.o

# target to build an object file
strconv.cpp.o:
	$(MAKE) -f CMakeFiles/themis.dir/build.make CMakeFiles/themis.dir/strconv.cpp.o
.PHONY : strconv.cpp.o

strconv.i: strconv.cpp.i

.PHONY : strconv.i

# target to preprocess a source file
strconv.cpp.i:
	$(MAKE) -f CMakeFiles/themis.dir/build.make CMakeFiles/themis.dir/strconv.cpp.i
.PHONY : strconv.cpp.i

strconv.s: strconv.cpp.s

.PHONY : strconv.s

# target to generate assembly for a file
strconv.cpp.s:
	$(MAKE) -f CMakeFiles/themis.dir/build.make CMakeFiles/themis.dir/strconv.cpp.s
.PHONY : strconv.cpp.s

strconv_tolower.o: strconv_tolower.cpp.o

.PHONY : strconv_tolower.o

# target to build an object file
strconv_tolower.cpp.o:
	$(MAKE) -f CMakeFiles/themis.dir/build.make CMakeFiles/themis.dir/strconv_tolower.cpp.o
.PHONY : strconv_tolower.cpp.o

strconv_tolower.i: strconv_tolower.cpp.i

.PHONY : strconv_tolower.i

# target to preprocess a source file
strconv_tolower.cpp.i:
	$(MAKE) -f CMakeFiles/themis.dir/build.make CMakeFiles/themis.dir/strconv_tolower.cpp.i
.PHONY : strconv_tolower.cpp.i

strconv_tolower.s: strconv_tolower.cpp.s

.PHONY : strconv_tolower.s

# target to generate assembly for a file
strconv_tolower.cpp.s:
	$(MAKE) -f CMakeFiles/themis.dir/build.make CMakeFiles/themis.dir/strconv_tolower.cpp.s
.PHONY : strconv_tolower.cpp.s

wstrconv_tolower.o: wstrconv_tolower.cpp.o

.PHONY : wstrconv_tolower.o

# target to build an object file
wstrconv_tolower.cpp.o:
	$(MAKE) -f CMakeFiles/themis.dir/build.make CMakeFiles/themis.dir/wstrconv_tolower.cpp.o
.PHONY : wstrconv_tolower.cpp.o

wstrconv_tolower.i: wstrconv_tolower.cpp.i

.PHONY : wstrconv_tolower.i

# target to preprocess a source file
wstrconv_tolower.cpp.i:
	$(MAKE) -f CMakeFiles/themis.dir/build.make CMakeFiles/themis.dir/wstrconv_tolower.cpp.i
.PHONY : wstrconv_tolower.cpp.i

wstrconv_tolower.s: wstrconv_tolower.cpp.s

.PHONY : wstrconv_tolower.s

# target to generate assembly for a file
wstrconv_tolower.cpp.s:
	$(MAKE) -f CMakeFiles/themis.dir/build.make CMakeFiles/themis.dir/wstrconv_tolower.cpp.s
.PHONY : wstrconv_tolower.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... themis"
	@echo "... strconv.o"
	@echo "... strconv.i"
	@echo "... strconv.s"
	@echo "... strconv_tolower.o"
	@echo "... strconv_tolower.i"
	@echo "... strconv_tolower.s"
	@echo "... wstrconv_tolower.o"
	@echo "... wstrconv_tolower.i"
	@echo "... wstrconv_tolower.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

