# msys-mingw-gcc.cmake

set(CMAKE_CROSSCOMPILING 1)
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_C_USE_RESPONSE_FILE_FOR_INCLUDES 0)
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES 0)

set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)


#eof
